USE Hospital_Management_System;
-- DROP TABLES
IF OBJECT_ID('INVOICE', 'U') IS NOT NULL DROP TABLE INVOICE;
IF OBJECT_ID('PATIENT_TESTS', 'U') IS NOT NULL DROP TABLE PATIENT_TESTS;
IF OBJECT_ID('TEST', 'U') IS NOT NULL DROP TABLE TEST;
IF OBJECT_ID('ADMITTED_PATIENT', 'U') IS NOT NULL DROP TABLE ADMITTED_PATIENT;
IF OBJECT_ID('ADMISSION', 'U') IS NOT NULL DROP TABLE ADMISSION;
IF OBJECT_ID('APPOINTMENT_PERSCRIPTION', 'U') IS NOT NULL DROP TABLE APPOINTMENT_PERSCRIPTION;
IF OBJECT_ID('APPOINTMENT_DISEASE', 'U') IS NOT NULL DROP TABLE APPOINTMENT_DISEASE;
IF OBJECT_ID('APPOINTMENT', 'U') IS NOT NULL DROP TABLE APPOINTMENT;
IF OBJECT_ID('PATIENT_CONTACT', 'U') IS NOT NULL DROP TABLE PATIENT_CONTACT;
IF OBJECT_ID('PATIENT', 'U') IS NOT NULL DROP TABLE PATIENT;
IF OBJECT_ID('EMPLOYEE_QUALIFICATION', 'U') IS NOT NULL DROP TABLE EMPLOYEE_QUALIFICATION;
IF OBJECT_ID('EMPLOYEE_CONTACT', 'U') IS NOT NULL DROP TABLE EMPLOYEE_CONTACT;
IF OBJECT_ID('EMPLOYEE', 'U') IS NOT NULL DROP TABLE EMPLOYEE;
IF OBJECT_ID('ROOMS', 'U') IS NOT NULL DROP TABLE ROOMS;

-- DROP ROLES/VIEWS
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'PATIENT_ROLE') DROP ROLE PATIENT_ROLE;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'RECEPTIONIST') DROP ROLE RECEPTIONIST;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'DOCTOR') DROP ROLE DOCTOR;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NURSE') DROP ROLE NURSE;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAB_TECHNICIAN') DROP ROLE LAB_TECHNICIAN;

IF OBJECT_ID('DOCTOR_VIEW', 'V') IS NOT NULL DROP VIEW DOCTOR_VIEW;
IF OBJECT_ID('PATIENT_VIEW', 'V') IS NOT NULL DROP VIEW PATIENT_VIEW;
IF OBJECT_ID('EMPLOYEE_VIEW', 'V') IS NOT NULL DROP VIEW EMPLOYEE_VIEW;
IF OBJECT_ID('PATIENT_APPOINTMENT', 'V') IS NOT NULL DROP VIEW PATIENT_APPOINTMENT;
IF OBJECT_ID('NURSE_PATIENT', 'V') IS NOT NULL DROP VIEW NURSE_PATIENT;

-- CREATE TABLES
CREATE TABLE ROOMS
(
    ROOM_ID INT NOT NULL,
    ROOM_TYPE VARCHAR(15),
    COUNT_OF_PERSONS INT,
    ROOM_CAPACITY INT,
    ROOM_AVAILABILITY VARCHAR(3) CHECK(ROOM_AVAILABILITY IN ('YES', 'NO')),
    CONSTRAINT ROOMS_PK PRIMARY KEY (ROOM_ID)
);

CREATE TABLE TEST
(
    TEST_ID INT NOT NULL,
    TEST_NAME VARCHAR(25),
    TEST_COST DECIMAL(6,2),
    CONSTRAINT TEST_PK PRIMARY KEY (TEST_ID)
);

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID VARCHAR(25) NOT NULL,
    EMPLOYEE_NAME VARCHAR(25),
    EMPLOYEE_DEPARTMENT VARCHAR(40),
    EMPLOYEE_DESIGNATION VARCHAR(25),
    ROOM_ID INT,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT EMPLOYEE_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);

CREATE TABLE EMPLOYEE_CONTACT
(
    EMPLOYEE_ID VARCHAR(25) NOT NULL,
    EMPLOYEE_CONTACT_NUMBER VARCHAR(15) NOT NULL,
    CONSTRAINT EMPLOYEE_CONTACT_PK PRIMARY KEY (EMPLOYEE_ID, EMPLOYEE_CONTACT_NUMBER),
    CONSTRAINT EMPLOYEE_CONTACT_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE EMPLOYEE_QUALIFICATION
(
    EMPLOYEE_ID VARCHAR(25) NOT NULL,
    QUALIFICATION VARCHAR(40) NOT NULL,
    CONSTRAINT EMPLOYEE_QUALIFICATION_PK PRIMARY KEY (EMPLOYEE_ID, QUALIFICATION),
    CONSTRAINT EMPLOYEE_QUALIFICATION_FK FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE PATIENT
(
    PATIENT_ID VARCHAR(25) NOT NULL,
    PATIENT_NAME VARCHAR(25),
    PATIENT_AGE INT,
    GENDER VARCHAR(1) CHECK(GENDER IN ('M', 'F')),
    CONSTRAINT PATIENT_PK PRIMARY KEY (PATIENT_ID)
);

CREATE TABLE PATIENT_CONTACT
(
    PATIENT_ID VARCHAR(25) NOT NULL,
    PATIENT_CONTACT_NUMBER VARCHAR(15) NOT NULL,
    CONSTRAINT PATIENT_CONTACT_PK PRIMARY KEY (PATIENT_ID, PATIENT_CONTACT_NUMBER),
    CONSTRAINT PATIENT_CONTACT_FK FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

CREATE TABLE APPOINTMENT
(
    APPOINTMENT_ID INT NOT NULL,
    EMPLOYEE_ID VARCHAR(25),
    PATIENT_ID VARCHAR(25),
    APPOINTMENT_DATE DATETIME DEFAULT GETDATE(),
    CONSTRAINT APPOINTMENT_PK PRIMARY KEY (APPOINTMENT_ID),
    CONSTRAINT APPOINTMENT_FK1 FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
    CONSTRAINT APPOINTMENT_FK2 FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);

CREATE TABLE APPOINTMENT_DISEASE
(
    APPOINTMENT_ID INT NOT NULL,
    DISEASE VARCHAR(25) NOT NULL,
    CONSTRAINT APPOINTMENT_DISEASE_PK PRIMARY KEY (APPOINTMENT_ID, DISEASE),
    CONSTRAINT APPOINTMENT_DISEASE_FK FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID)
);

CREATE TABLE APPOINTMENT_PERSCRIPTION
(
    APPOINTMENT_ID INT NOT NULL,
    MEDICINE_NAME VARCHAR(25) NOT NULL,
    DOSAGE VARCHAR(40),
    DURATION VARCHAR(25),
    CONSTRAINT APPOINTMENT_PERSCRIPTION_PK PRIMARY KEY (APPOINTMENT_ID, MEDICINE_NAME),
    CONSTRAINT APPOINTMENT_PERSCRIPTION_FK FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID)
);

CREATE TABLE ADMISSION
(
    ADMISSION_ID INT NOT NULL,
    APPOINTMENT_ID INT,
    ROOM_ID INT,
    ADMISSION_DATE DATETIME DEFAULT GETDATE(),
    DISCHARGE_DATE DATETIME,
    CONSTRAINT ADMISSION_PK PRIMARY KEY (ADMISSION_ID),
    CONSTRAINT ADMISSION_FK1 FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID),
    CONSTRAINT ADMISSION_FK2 FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)
);

CREATE TABLE ADMITTED_PATIENT
(
    PATIENT_ID VARCHAR(25) NOT NULL,
    ADMISSION_ID INT NOT NULL,
    CONSTRAINT ADMITTED_PATIENT_PK PRIMARY KEY (PATIENT_ID, ADMISSION_ID),
    CONSTRAINT ADMITTED_PATIENT_FK1 FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    CONSTRAINT ADMITTED_PATIENT_FK2 FOREIGN KEY (ADMISSION_ID) REFERENCES ADMISSION(ADMISSION_ID)
);

CREATE TABLE PATIENT_TESTS
(
    PATIENT_ID VARCHAR(25) NOT NULL,
    TEST_ID INT NOT NULL,
    TEST_DATE DATETIME DEFAULT GETDATE() NOT NULL,
    RESULT_DATE DATETIME,
    TEST_RESULT VARCHAR(15),
    CONSTRAINT PATIENT_TESTS_PK PRIMARY KEY (PATIENT_ID, TEST_ID, TEST_DATE),
    CONSTRAINT PATIENT_TESTS_FK1 FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    CONSTRAINT PATIENT_TESTS_FK2 FOREIGN KEY (TEST_ID) REFERENCES TEST(TEST_ID)
);

CREATE TABLE INVOICE
(
    INVOICE_ID INT NOT NULL,
    PATIENT_ID VARCHAR(25),
    COST DECIMAL(10,2),
    PAYMENT_METHOD VARCHAR(25),
    CONSTRAINT INVOICE_PK PRIMARY KEY (INVOICE_ID),
    CONSTRAINT INVOICE_FK FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);


-- DROP ROLES/VIEWS
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'PATIENT_ROLE') DROP ROLE PATIENT_ROLE;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'RECEPTIONIST') DROP ROLE RECEPTIONIST;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'DOCTOR') DROP ROLE DOCTOR;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NURSE') DROP ROLE NURSE;
IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAB_TECHNICIAN') DROP ROLE LAB_TECHNICIAN;

IF OBJECT_ID('DOCTOR_VIEW', 'V') IS NOT NULL DROP VIEW DOCTOR_VIEW;
IF OBJECT_ID('PATIENT_VIEW', 'V') IS NOT NULL DROP VIEW PATIENT_VIEW;
IF OBJECT_ID('EMPLOYEE_VIEW', 'V') IS NOT NULL DROP VIEW EMPLOYEE_VIEW;
IF OBJECT_ID('PATIENT_APPOINTMENT', 'V') IS NOT NULL DROP VIEW PATIENT_APPOINTMENT;
IF OBJECT_ID('NURSE_PATIENT', 'V') IS NOT NULL DROP VIEW NURSE_PATIENT;

-- CREATE VIEWS (Separate each CREATE VIEW into a new batch with GO)
GO

CREATE VIEW DOCTOR_VIEW AS
SELECT E.EMPLOYEE_NAME, E.EMPLOYEE_DEPARTMENT, E.EMPLOYEE_DESIGNATION, Q.QUALIFICATION, E.ROOM_ID
FROM EMPLOYEE E
JOIN EMPLOYEE_QUALIFICATION Q ON E.EMPLOYEE_ID = Q.EMPLOYEE_ID
WHERE E.EMPLOYEE_NAME LIKE 'Dr%';

GO

CREATE VIEW PATIENT_VIEW AS
SELECT P.PATIENT_ID, P.PATIENT_NAME, P.PATIENT_AGE, P.GENDER, C.PATIENT_CONTACT_NUMBER
FROM PATIENT P
JOIN PATIENT_CONTACT C ON P.PATIENT_ID = C.PATIENT_ID;

GO

CREATE VIEW EMPLOYEE_VIEW AS
SELECT E.EMPLOYEE_NAME, E.EMPLOYEE_DEPARTMENT, E.EMPLOYEE_DESIGNATION, Q.QUALIFICATION, C.EMPLOYEE_CONTACT_NUMBER, E.ROOM_ID
FROM EMPLOYEE E
JOIN EMPLOYEE_CONTACT C ON E.EMPLOYEE_ID = C.EMPLOYEE_ID
JOIN EMPLOYEE_QUALIFICATION Q ON E.EMPLOYEE_ID = Q.EMPLOYEE_ID;

GO

CREATE VIEW PATIENT_APPOINTMENT AS
SELECT A.PATIENT_ID, A.APPOINTMENT_DATE, D.DISEASE, P.MEDICINE_NAME, P.DOSAGE, P.DURATION
FROM APPOINTMENT A
JOIN APPOINTMENT_DISEASE D ON A.APPOINTMENT_ID = D.APPOINTMENT_ID
JOIN APPOINTMENT_PERSCRIPTION P ON A.APPOINTMENT_ID = P.APPOINTMENT_ID;

GO

CREATE VIEW NURSE_PATIENT AS
SELECT A.PATIENT_ID, AD.ADMISSION_DATE, D.DISEASE, P.MEDICINE_NAME, P.DOSAGE, P.DURATION
FROM APPOINTMENT A
JOIN APPOINTMENT_DISEASE D ON A.APPOINTMENT_ID = D.APPOINTMENT_ID
JOIN APPOINTMENT_PERSCRIPTION P ON A.APPOINTMENT_ID = P.APPOINTMENT_ID
JOIN ADMISSION AD ON A.APPOINTMENT_ID = AD.APPOINTMENT_ID;

GO

-- CREATE ROLES AND PRIVILEGES (This part stays as is)
CREATE ROLE PATIENT_ROLE;
GRANT SELECT, INSERT, UPDATE (PATIENT_NAME, PATIENT_AGE, GENDER, PATIENT_CONTACT_NUMBER) ON PATIENT_VIEW TO PATIENT_ROLE;
GRANT SELECT ON TEST TO PATIENT_ROLE;
GRANT SELECT ON DOCTOR_VIEW TO PATIENT_ROLE;

GO

CREATE ROLE RECEPTIONIST;
GRANT INSERT, SELECT, UPDATE ON PATIENT TO RECEPTIONIST;
GRANT SELECT ON EMPLOYEE_VIEW TO RECEPTIONIST;
GRANT SELECT ON ROOMS TO RECEPTIONIST;
GRANT SELECT, INSERT, UPDATE, DELETE ON APPOINTMENT TO RECEPTIONIST;
GRANT SELECT ON TEST TO RECEPTIONIST;
GRANT INSERT, SELECT, UPDATE ON ADMISSION TO RECEPTIONIST;
GRANT INSERT, SELECT, UPDATE ON INVOICE TO RECEPTIONIST;

GO

CREATE ROLE DOCTOR;
GRANT SELECT, INSERT, UPDATE ON PATIENT_APPOINTMENT TO DOCTOR;

GO

CREATE ROLE NURSE;
GRANT SELECT ON NURSE_PATIENT TO NURSE;

GO

CREATE ROLE LAB_TECHNICIAN;
GRANT SELECT, INSERT, UPDATE ON PATIENT_TESTS TO LAB_TECHNICIAN;
GRANT SELECT ON TEST TO LAB_TECHNICIAN;

GO


-- INSERTING DATA INTO THE ROOMS TABLE
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (201, 'DOCTOR ROOM', 0, 3, 'YES');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (202, 'DOCTOR ROOM', 0, 3, 'YES');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (203, 'WARD', 0, 15, 'YES');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (204, 'DOCTOR ROOM', 0, 3, 'YES');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (205, 'PRIVATE', 0, 1, 'YES');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (206, 'PRIVATE', 0, 1, 'YES');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE) VALUES (207, 'LAB');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (208, 'PRIVATE', 0, 1, 'YES');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE) VALUES (209, 'LAB');
INSERT INTO ROOMS (ROOM_ID, ROOM_TYPE, COUNT_OF_PERSONS, ROOM_CAPACITY, ROOM_AVAILABILITY) 
VALUES (210, 'WARD', 0, 15, 'YES');

-- INSERTING DATA INTO THE EMPLOYEE TABLE
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION, ROOM_ID) 
VALUES ('E001', 'Dr. Hasan', 'Cardiology', 'Senior Doctor', 201);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION, ROOM_ID) 
VALUES ('E002', 'Dr. Sara', 'Neurology', 'Senior Doctor', 202);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION) 
VALUES ('E003', 'Imran Khan', 'Helping Staff', 'Receptionist');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION, ROOM_ID) 
VALUES ('E004', 'Dr. Ali Akbar', 'Pediatrics', 'Junior Doctor', 204);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION) 
VALUES ('E005', 'Sana Yousaf', 'Helping Staff', 'Receptionist');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION, ROOM_ID) 
VALUES ('E006', 'Dr. Zafar Iqbal', 'Oncology', 'Surgeon', 204);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION) 
VALUES ('E007', 'Nadia Bashir', 'Medical Staff', 'Nurse');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION) 
VALUES ('E008', 'Khalid Waleed', 'Medical Staff', 'Nurse');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION, ROOM_ID) 
VALUES ('E009', 'Dr. Faisal', 'Cardiology', 'Senior Doctor', 201);
INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_DEPARTMENT, EMPLOYEE_DESIGNATION, ROOM_ID) 
VALUES ('E010', 'Dr. Anum Akram', 'Neurology', 'Surgeon', 202);

-- INSERTING DATA INTO THE EMPLOYEE_CONTACT TABLE
INSERT INTO EMPLOYEE_CONTACT VALUES ('E001', '03111234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E002', '03112234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E003', '03113234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E004', '03114234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E005', '03115234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E006', '03116234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E007', '03117234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E008', '03118234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E009', '03119234567');
INSERT INTO EMPLOYEE_CONTACT VALUES ('E010', '03120234567');

-- INSERTING DATA INTO THE EMPLOYEE_QUALIFICATION TABLE
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E001', 'MBBS');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E002', 'MBBS');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E003', 'BSN');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E004', 'MBBS');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E005', 'BSN');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E006', 'MBBS');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E006', 'MS');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E007', 'GNM');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E008', 'GNM');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E009', 'MBBS');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E010', 'MBBS');
INSERT INTO EMPLOYEE_QUALIFICATION VALUES ('E010', 'MS');

-- INSERTING DATA INTO THE PATIENT TABLE
INSERT INTO PATIENT VALUES ('P001', 'Ahmed Ali', 45, 'M');
INSERT INTO PATIENT VALUES ('P002', 'Ayesha Khan', 30, 'F');
INSERT INTO PATIENT VALUES ('P003', 'Mohammed Farhan', 28, 'M');
INSERT INTO PATIENT VALUES ('P004', 'Zainab Siddiqui', 40, 'F');
INSERT INTO PATIENT VALUES ('P005', 'Hamza Qureshi', 50, 'M');
INSERT INTO PATIENT VALUES ('P006', 'Fatima Noor', 35, 'F');
INSERT INTO PATIENT VALUES ('P007', 'Bilal Ahmed', 25, 'M');
INSERT INTO PATIENT VALUES ('P008', 'Maryam Zafar', 32, 'F');
INSERT INTO PATIENT VALUES ('P009', 'Usman Tariq', 42, 'M');
INSERT INTO PATIENT VALUES ('P010', 'Rania Javed', 29, 'F');

-- INSERTING DATA INTO THE PATIENT_CONTACT TABLE
INSERT INTO PATIENT_CONTACT VALUES ('P001', '03001234567');
INSERT INTO PATIENT_CONTACT VALUES ('P002', '03002345678');
INSERT INTO PATIENT_CONTACT VALUES ('P003', '03003456789');
INSERT INTO PATIENT_CONTACT VALUES ('P004', '03004567890');
INSERT INTO PATIENT_CONTACT VALUES ('P005', '03005678901');
INSERT INTO PATIENT_CONTACT VALUES ('P006', '03006789012');
INSERT INTO PATIENT_CONTACT VALUES ('P007', '03007890123');
INSERT INTO PATIENT_CONTACT VALUES ('P008', '03008901234');
INSERT INTO PATIENT_CONTACT VALUES ('P009', '03009012345');
INSERT INTO PATIENT_CONTACT VALUES ('P010', '03000123456');

-- INSERTING DATA INTO THE APPOINTMENT TABLE
INSERT INTO APPOINTMENT VALUES (1, 'E001', 'P001', GETDATE());
INSERT INTO APPOINTMENT VALUES (2, 'E002', 'P002', GETDATE());
INSERT INTO APPOINTMENT VALUES (4, 'E004', 'P004', GETDATE());
INSERT INTO APPOINTMENT VALUES (6, 'E006', 'P006', GETDATE());
INSERT INTO APPOINTMENT VALUES (9, 'E009', 'P009', GETDATE());
INSERT INTO APPOINTMENT VALUES (10,'E001', 'P010', GETDATE());

-- INSERTING DATA INTO THE APPOINTMENT_DISEASE TABLE
INSERT INTO APPOINTMENT_DISEASE VALUES (1, 'Hypertension');
INSERT INTO APPOINTMENT_DISEASE VALUES (2, 'Diabetes');
INSERT INTO APPOINTMENT_DISEASE VALUES (4, 'Pneumonia');
INSERT INTO APPOINTMENT_DISEASE VALUES (6, 'Gastritis');
INSERT INTO APPOINTMENT_DISEASE VALUES (9, 'Cholesterol');
INSERT INTO APPOINTMENT_DISEASE VALUES (10, 'Migraine');

-- INSERTING DATA INTO THE APPOINTMENT_PERSCRIPTION TABLE
INSERT INTO APPOINTMENT_PERSCRIPTION VALUES (1, 'Paracetamol', '500mg', '7 days');
INSERT INTO APPOINTMENT_PERSCRIPTION VALUES (2, 'Amoxicillin', '250mg', '10 days');
INSERT INTO APPOINTMENT_PERSCRIPTION VALUES (4, 'Ciprofloxacin', '500mg', '7 days');
INSERT INTO APPOINTMENT_PERSCRIPTION VALUES (6, 'Pantoprazole', '20mg', '14 days');
INSERT INTO APPOINTMENT_PERSCRIPTION VALUES (9, 'Atorvastatin', '10mg', '1 month');
INSERT INTO APPOINTMENT_PERSCRIPTION VALUES (10, 'Lisinopril', '10mg', '7 days');

-- INSERTING DATA INTO THE ADMISSION TABLE
INSERT INTO ADMISSION (ADMISSION_ID, APPOINTMENT_ID, ROOM_ID, ADMISSION_DATE) VALUES (101, 1, 203, GETDATE());
INSERT INTO ADMISSION VALUES (103, 4, 205, GETDATE(), '2024-12-25');
INSERT INTO ADMISSION (ADMISSION_ID, APPOINTMENT_ID, ROOM_ID, ADMISSION_DATE) VALUES (104, 6, 206, GETDATE());
INSERT INTO ADMISSION (ADMISSION_ID, APPOINTMENT_ID, ROOM_ID, ADMISSION_DATE) VALUES (105, 9, 210, GETDATE());
INSERT INTO ADMISSION VALUES (106, 10, 210, GETDATE(), '2024-12-30');

-- INSERTING DATA INTO THE TEST TABLE
INSERT INTO TEST VALUES (1, 'Blood Test', 500);
INSERT INTO TEST VALUES (2, 'X-Ray', 1500);
INSERT INTO TEST VALUES (3, 'MRI', 5000);
INSERT INTO TEST VALUES (4, 'CT Scan', 8000);
INSERT INTO TEST VALUES (5, 'Urine Test', 300);
INSERT INTO TEST VALUES (6, 'Ultrasound', 2000);
INSERT INTO TEST VALUES (7, 'ECG', 1000);
INSERT INTO TEST VALUES (8, 'Lipid Profile', 4000);
INSERT INTO TEST VALUES (9, 'Thyroid Test', 2500);
INSERT INTO TEST VALUES (10, 'Diabetes Test', 800);

-- INSERTING DATA INTO THE PATIENT_TESTS TABLE
INSERT INTO PATIENT_TESTS (PATIENT_ID, TEST_ID, TEST_DATE) VALUES ('P001', 1, GETDATE());
INSERT INTO PATIENT_TESTS VALUES ('P001', 2, GETDATE(), '2024-12-24', 'Negative');
INSERT INTO PATIENT_TESTS VALUES ('P003', 4, GETDATE(), '2024-12-20', 'Negative');
INSERT INTO PATIENT_TESTS (PATIENT_ID, TEST_ID, TEST_DATE) VALUES ('P004', 2, GETDATE());
INSERT INTO PATIENT_TESTS VALUES ('P002', 3, GETDATE(), '2024-12-19', 'Negative');
INSERT INTO PATIENT_TESTS (PATIENT_ID, TEST_ID, TEST_DATE) VALUES ('P005', 6, GETDATE());
INSERT INTO PATIENT_TESTS VALUES ('P009', 10, GETDATE(), '2024-12-25', 'Negative');

-- INSERTING DATA INTO THE INVOICE TABLE
INSERT INTO INVOICE VALUES (1001, 'P001', 1500.00, 'Credit Card');
INSERT INTO INVOICE VALUES (1002, 'P002', 2000.00, 'Cash');
INSERT INTO INVOICE VALUES (1004, 'P004', 2200.00, 'Cash');
INSERT INTO INVOICE VALUES (1006, 'P006', 1600.00, 'Debit Card');
INSERT INTO INVOICE VALUES (1009, 'P009', 2100.00, 'Debit Card');
INSERT INTO INVOICE VALUES (1010, 'P010', 2300.00, 'Credit Card');